
services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-bullyguard}"
    image: bullyguard-data-processing
    container_name: bullyguard-data-processing-container
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=./creds/ml-project-447013-8e95deb1e8f4.json
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-bar3126}"
        USER_ID: "${USER_ID:-1000}"
    volumes:
      - ./:/app/
      - ~/.config/gcloud/:/home/${USER_NAME}/.config/gcloud
    ports:
      - 8080:8080
      - 8888:8888

    init: true
    ipc: host
      